### ISSUE TITLE
Allow changing the URL of wasmPaths and tokenizers .wasm files

### ISSUE THREAD

**Issue by GarciaLnk** [visheratin/web-ai#11]
Right now, the URL of the files that provide the .wasm files for wasmPaths and tokenizers are hard-coded in the library, ideally these URLs should be configurable by a developer using this library to not rely on third-party servers.

**Comment by visheratin** [comment]
In the latest release (0.7.0), you can find these parameters in the `SessionParams` global variable.

**Comment by visheratin** [comment]
Please be aware that ORT WASM files are version dependent - if you try to use the files from a different version, they will throw an obscure error with no details. The current version of the package uses version 1.14.0 of ONNX runtime.

**Comment by GarciaLnk** [comment]
I'll be using the .wasm files provided in whatever version of onnxruntime-web's npm package that web-ai is using, so I don't think version tracking is an issue.

I'm closing this as solved.
