### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by rifkyniyas** [visheratin/web-ai#14]
I am trying to use web-ai along with [voy](https://github.com/tantaraio/voy). I tried with the example code given in the documentation and ended up with following error.
```
SyntaxError: Unexpected token 'export'
<unknown>
file:///path/to/project/node_modules/%20(visheratin/web-ai/dist/index.js (1)
```
I tried removing all the code except the first line
```
import { TextModel } from "@visheratin/web-ai";
```
The version of  web-ai I am using is `0.7.4`. I even tried switching to the working version in the [examples files](https://github.com/visheratin/web-ai/tree/main/examples/nextjs) to version `0.7.2` But still the exact problem persists

**Comment by visheratin** [comment]
Thank you for reporting the issue. Can you describe your setup in more detail? Are you working on a web application or maybe a browser extension? Do you use TypeScript or JavaScript? Do you use bundlers for your project?

**Comment by rifkyniyas** [comment]
Sure. I am working on a web application using Next.js version `13.2.4`. I am using only JavaScript and I don't use any bundlers

**Comment by visheratin** [comment]
One of the reasons for that may be that Web AI needs to be transpiled into JavaScript. Did you try [setting](https://github.com/visheratin/web-ai/blob/main/examples/nextjs/next.config.js#L6) this option in the `next.config.js` file?

**Comment by rifkyniyas** [comment]
Now the above error seems to be fixed. I am afraid that I didn't see the above in the documentation. Am I missing something or does this has to be included in the docs?

Thank you. Consider this issue to be closed as for now
