### ISSUE TITLE
A demo site

### ISSUE THREAD

**Issue by volkancirik** [visheratin/web-ai#2]
Hello,

Not an expert in web development. I try to create a demo, but I get the following error:

```
Aborted(Error: ENOENT: no such file or directory, open 'https:/edge-ai-models.s3.us-east-2.amazonaws.com/onnx-13/ort-wasm-simd-threaded.wasm')
failed to asynchronously prepare wasm: RuntimeError: Aborted(Error: ENOENT: no such file or directory, open 'https:/edge-ai-models.s3.us-east-2.amazonaws.com/onnx-13/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.
Aborted(RuntimeError: Aborted(Error: ENOENT: no such file or directory, open 'https:/edge-ai-models.s3.us-east-2.amazonaws.com/onnx-13/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.)
```

Would you mind creating a very simple single webpage demo on the GitHub repo?

**Comment by visheratin** [comment]
Hi!

[Here](https://codesandbox.io/p/sandbox/boring-pine-fyn75o) is the demo for image classification. Right now, I'm working on a set of demo pages for all supported use cases. You can find it in [another branch](https://github.com/visheratin/web-ai/tree/examples/examples/nextjs). At the moment, all examples are for Next.js, as I'm most familiar with it.

If these examples don't help, please share the code you are trying to run.

**Comment by volkancirik** [comment]
Thanks for the prompt response! I'll check out the other branch!
