### ISSUE TITLE
ORT environment variables are not accessible through this library

### ISSUE THREAD

**Issue by GarciaLnk** [visheratin/web-ai#7]
Ideally, a developer should be able to modify the environment variables of the ONNX runtime even if they're using this library.

This is relevant to me because I'm writing a browser extension using this library, and I found out that there's an open issue (https://github.com/microsoft/onnxruntime/issues/14445) with how ORT behaves in an MV3 extension, and to work around it for now the only solution is to run ORT on one thread, setting `ort.env.wasm.numThreads=1 `.

**Comment by visheratin** [comment]
Will `numThreads` be sufficient, or would you want to modify some other parameters?

**Comment by GarciaLnk** [comment]
In this case, numThreads would be sufficient

**Comment by visheratin** [comment]
With the new version (0.5.4) of the package, you can set the `numThreads` parameter using the exported variable `SessionParams`:
```
SessionParams.numThreads = 1;
```

Let me know if it works for you.

**Comment by GarciaLnk** [comment]
This works fine, closing the issue.
