### ISSUE TITLE
Add resource consumption guardrails

### ISSUE THREAD

**Issue by visheratin** [visheratin/web-ai#9]
Need to implement a mechanism that will limit the CPU and RAM usage of the library.

**Comment by GarciaLnk** [comment]
Disk usage should also be taken into account, since a few large models can push the size of the indexedDB into the GBs without notice.

**Comment by visheratin** [comment]
Sorry, I didn't read `localforage` docs carefully enough. In the latest release (0.7.0), the cache size parameter was moved to the `SessionParams` and actually affects the size of the cache.
